### DISCUSSION TITLE
running livekit on raspbian

### DISCUSSION THREAD

**Discussion by muggel042** [bekriebel/fvtt-module-avclient-livekit#60] [Q&A]
Hello

I've recently spent some time getting this to work and thought I'd share how to run livekit without docker on raspbian. This works pretty well for me and my FoundryVTT group.

Prerequisites
- raspbian is installed as 64bit version (supported CPUs: https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/ )
  run getconf LONG_BIT to test, which should give a 64 for 64 bit OS and 32 for 32 bit OS
- local install of go > 1.18

I'm running livekit on a dedicated user named "livekit" in his own home directory. Change pathes, as required for your installation.
Install via following steps:
```
git clone https://github.com/livekit/livekit
cd livekit/
export PATH=$PATH:/usr/local/go/bin:/home/livekit/go/bin
mkdir /home/livekit/go/
export GOPATH=$HOME/go
./bootstrap.sh
mage
```

Here is my working livekit-config.yaml
```
port: 7880
rtc:
    #port_range_start: 50000
    #port_range_end: 50100
    tcp_port: 7881
    udp_port: 7882

prometheus_port: 6789

turn:
    enabled: true
    udp_port: 3478
    tls_port: 5349
    external_tls: true
    domain: livekit-turn.example.com
```

If reverse proxy is set up correctly (as already documented) install can be tested using https://meet.livekit.io via custom tab.
Create a token via livekit-cli ( https://github.com/livekit/livekit-cli )

```
livekit-cli create-token --api-key xxx --api-secret yyyyyyyyy --join --room testroom --identity musterfrau -valid-for 24h
```
